name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
      - name: Installdeps
        run: sudo apt update && sudo apt install just
        
      - name: Get a newer podman for heredoc support (from debian testing)
        run: |
          set -eux
          echo 'deb [trusted=yes] https://ftp.debian.org/debian/ testing main' | sudo tee /etc/apt/sources.list.d/testing.list
          sudo apt update
          sudo apt install -y crun/testing podman/testing skopeo/testing

      - name: build
        run: sudo just build

      - name: units
        run: sudo just unittest
        
      - name: Push the container image
        if: github.event_name == 'push'
        run: podman push ghcr.io/bootc-dev/kit